config/routes.rb
Rails.application.routes.draw do
  root 'posts#index'

  get 'categories/export', to: 'categories#export'
  get 'categories/import', to: 'categories#import'
  post 'categories/import', to: 'categories#import_file'
  get 'posts/export', to: 'posts#export'
  get 'posts/import', to: 'posts#import'
  post 'posts/import', to: 'posts#import_file'
  resources :posts do
    get '/page/:page', action: :index, on: :collection
  end
  resources :users, only: %i[new create]
  resources :categories


  # get 'users/new'
  # get 'users/create'

  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  get 'welcome', to: 'sessions#welcome'
  delete '/logout',  to: 'sessions#destroy'
  get 'authorized', to: 'sessions#page_requires_login'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/post.rb
require 'csv'
class Post < ApplicationRecord
  belongs_to :category
  has_one_attached :image, dependent: :destroy
  paginates_per 2

  validates :title, presence: { message: "Post title can't be blank" },
                    length: { minimum: 10, too_short: '%<count>s characters is the minimum allowed', maximum: 30, too_long: '%<count>s characters is the maximum allowed'}
  validates :content, presence: { message: "Content can't be blank" }, length: { minimum: 50, too_short: '%<count>s characters is the minimum allowed' }
  # validates :category_id, presence: true
  validates :category_id, presence: { message: 'choose one category!' }
  validates :image, attached: true,
                    processable_image: true,
                    content_type: ['image/png', 'image/jpeg', 'image/jpg']

  def self.to_csv
    attributes = %w[id title content category_id]

    CSV.generate(headers: true) do |csv|
      csv << attributes

      all.find_each do |post|
        csv << attributes.map { |attr| post.send(attr) }
      end
    end
  end

  def self.import(file)
    opened_file = File.open(file)
    options = { headers: true, col_sep: ',' }
    begin
      CSV.foreach(opened_file, **options) do |row|
        post = Post.create(title: row['title'], content: row['content'], category_id: row['category_id'])

        post.image.attach(io: File.open(Rails.root.join('app', 'assets', 'images', 'images.png')),
                          filename: 'images.png', content_type: 'image/png')
        raise StandardError, 'error' unless post.save
      end
    rescue StandardError => e
      e.message
    end
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  def index
    @posts = PostsService.listAll.page params[:page]
    # @posts = Post.all
  end

  def show
    @post = PostsService.findPostById(params[:id])
  end

  def new
    @post = PostsService.newPost
    @categories = Category.all
  end

  def create
    @post = PostsService.createPost(post_params)
    @categories = CategoriesService.listAll
    if @post.save
      render json: @post, status: :created
      # # @post.save
      # flash[:notice] = 'The new post was saved successfully!'
      # redirect_to posts_path
    else
      # binding.pry
      @post.image = nil
      render :new
    end
  end

  def edit
    @post = PostsService.findPostById(params[:id])
    @categories = CategoriesService.listAll
  end

  def update
    @isUpdatePost = PostsService.updatePost(params[:id], post_params)
    if @isUpdatePost
      flash[:notice] = 'The selected post was updated!'
      redirect_to posts_path
    else
      flash[:notice] = 'Please fill correct data!'
      @post = PostsService.findPostById(params[:id])
      # redirect_to request.referer
      render :edit
    end
  end

  def destroy
    PostsService.deletePost(params[:id])
    flash[:notice] = 'The selected post was deleted successfully!'
    redirect_to posts_path
  end

  def export
    @posts = Post.select(:id, :title, :content, :category_id)

    respond_to do |format|
      format.html
      format.csv { send_data @posts.to_csv, filename: "posts-#{Date.today}.csv" }
    end
  end

  def import; end

  def import_file
    return redirect_to request.referer, notice: 'No file added' if params[:file].nil?
    return redirect_to request.referer, notice: 'Only CSV files allowed' unless params[:file].content_type == 'text/csv'

    msg = Post.import(params[:file])
    if msg != 'error'
      redirect_to posts_path
    else
      flash.now[:notice] = 'Errors occured!'
      render :import
    end

    # else
    #   flash[:notice] = 'Errors occured!'
    #   render :import
    # end
  end

  private

  def post_params
    params.require(:post).permit(:title, :content, :category_id, :image)
  end
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/posts/_form.html.erb
<%= bootstrap_form_for(post) do |f| %>
  <% flash.each do |name, msg| %>
    <div class="text-danger">
      *<%= msg %>
    </div>
  <% end %>
  <div id="target">
    <%= image_tag post.image.attached? ? post.image : "default-image.jpg",
    style: "width: 100px; display: inline-block",
    id: "preview-image" %>
  </div>
  <%= f.text_field :title, label: "Title", placeholder: "Enter post title" %>
  <%= f.text_area :content, label: "Content", placeholder: "Content" %>
  <%= f.collection_select :category_id,
                      categories,
                      :id,
                      :name,
                      include_blank: "Select a value" %>
  <%= f.file_field :image, label: "Image", placeholder: "Choose image file:" %>

  <%= f.submit "Save", class: ["btn btn-sm btn-primary"] %>
<% end %>

app/views/posts/destroy.html.erb
<h1>Posts#destroy</h1>
<p>Find me in app/views/posts/destroy.html.erb</p>

app/views/posts/edit.html.erb
<div class="container">
  <div class="row mt-5">
    <div class="col-6 mx-auto px-3">
      <div class="card">
        <div class="card-header">
          <h5 class="fw-bolder">Post Edit</h5>
        </div>
        <div class="card-body">
          <%= render "form", post: @post, categories: @categories %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/posts/import.html.erb
<div class="container">
  <div class="row mt-5">
    <div class="col-6 mx-auto">
      <div class="card">
        <div class="card-header">
          <h5 class="fw-bolder">Post Import</h5>
        </div>
        <div class="card-body">
          <% flash.each do |name, msg| %>
            <div class="text-danger mb-3">
              *<%= msg %>
            </div>
          <% end %>
          <%= form_tag posts_import_path, method: :post, multipart: true do %>
            <%= file_field_tag :file, accept: ".csv" %>
            <%= submit_tag "⚙️ Import" %>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/posts/index.html.erb
<div class="container">
  <div class="row mt-3">
    <div class="col-8 mx-auto">
      <% flash.each do |name, msg| %>
        <div class="alert alert-sm alert-success" role="alert">
          <%= msg %>
        </div>
      <% end %>
    </div>
  </div>
  <div class="row mt-3">
    <div class="col-8 mx-auto">
      <div class="mb-3">
        <%= link_to "Create", new_post_path, method: :get, class: "btn btn-sm btn-primary" %>
        <%= link_to "Export",
        posts_export_path(format: "csv"),
        method: :get,
        class: "btn btn-sm btn-info" %>
        <%= link_to "Import",
        posts_import_path,
        method: :get,
        class: "btn btn-sm btn-secondary" %>
      </div>
      <table class="table table-striped table-hover">
        <thead>
          <tr>
            <th scope="col">#</th>
            <th scope="col">Title</th>
            <th scope="col">Image</th>
            <th scope="col" style="width: 30%;">Content</th>
            <th scope="col">Category</th>
            <th scope="col">
              Actions
            </th>
          </tr>
        </thead>
        <tbody>
          <% @posts.each do |p| %>
            <tr>
              <th scope="row"><%= p.id %></th>
              <td><%= p.title %></td>
              <td>
                <%= image_tag p.image, style: "width: 100px; display: inline-block" %>
              </td>
              <td style="width: 30%;">
                <%= truncate(p.content, length: 50) %>
              </td>
              <td>
                <%= p.category.name %>
              </td>
              <td>
                <%= link_to "Details",
                "/posts/#{p.id}",
                method: :get,
                class: "btn btn-sm btn-outline-secondary me-2 mb-sm-2" %>
                <%= link_to "Edit",
                "/posts/#{p.id}/edit",
                method: :get,
                class: "btn btn-sm btn-outline-success me-2 mb-sm-2" %>
                <%= button_to "Delete",
                post_path(p),
                data: {
                  confirm: "Are you sure?",
                  turbo_confirm: "Are you sure?"
                },
                method: :delete,
                class: "btn btn-sm btn-outline-danger" %>
              </td>
            </tr>
          <% end %>
        </tbody>
      </table>
      <%= paginate @posts %>
    </div>
  </div>
</div>

app/views/posts/new.html.erb
<div class="container">
  <div class="row mt-5">
    <div class="col-6 mx-auto">
      <div class="card">
        <div class="card-header">
          <h5 class="fw-bolder">Post Create</h5>
        </div>
        <div class="card-body">
          <%= render "form", post: @post, categories: @categories %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/posts/show.html.erb
<div class="container">
  <div class="row mt-5">
    <div class="card p-3" style="width: 700px">
      <div class="row">
        <div class="col-5">
            <%= image_tag @post.image, style: "width: 100%; display: inline-block" %>
        </div>
        <div class="col-7">
            <div class="card-body">
                <h5>
                    <%= @post.title.capitalize() %>
                </h5>
                <small> created 
                    <span class="text-primary"><%= time_ago_in_words(@post.created_at) %></span> ago
                </small>
                <p>Category : 
                    <span class="badge bg-secondary">
                        <%= @post.category.name %>
                    </span>
                </p>
                <p class="py-3">
                    <%= @post.content %>
                </p>
            </div>
        </div>
      </div>
    </div>
  </div>
</div>