config/routes.rb
Rails.application.routes.draw do
  root 'posts#index'

  get 'categories/export', to: 'categories#export'
  get 'categories/import', to: 'categories#import'
  post 'categories/import', to: 'categories#import_file'
  get 'posts/export', to: 'posts#export'
  get 'posts/import', to: 'posts#import'
  post 'posts/import', to: 'posts#import_file'
  resources :posts do
    get '/page/:page', action: :index, on: :collection
  end
  resources :users, only: %i[new create]
  resources :categories


  # get 'users/new'
  # get 'users/create'

  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  get 'welcome', to: 'sessions#welcome'
  delete '/logout',  to: 'sessions#destroy'
  get 'authorized', to: 'sessions#page_requires_login'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/category.rb
require 'csv'
class Category < ApplicationRecord
  has_many :posts, dependent: :destroy
  validates_associated :posts
  validates :name, presence: true

  def self.to_csv
    attributes = %w[id name]

    CSV.generate(headers: true) do |csv|
      csv << attributes

      all.find_each do |category|
        csv << attributes.map { |attr| category.send(attr) }
      end
    end
  end

  def self.import(file)
    opened_file = File.open(file)
    options = { headers: true, col_sep: ',' }
    begin
      CSV.foreach(opened_file, **options) do |row|
        # map the CSV columns to your database columns
        category_hash = {}
        category_hash[:name] = row['name']

        category = Category.create(category_hash)
        raise StandardError, 'error' unless category.save
      end
    rescue StandardError => e
      e.message
    end
  end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  def index
    @categories = CategoriesService.listAll
  end

  def new
    @category = CategoriesService.newCategory
  end

  def create
    @isSaveCategory = CategoriesService.createCategory(category_params)
    if @isSaveCategory
      flash[:notice] = 'The new category was saved successfully!'
      redirect_to categories_path
    else
      # redirect_to new_categories_path
      render :new
    end
  end

  def edit
    @category = CategoriesService.findCategoryById(params[:id])
  end

  def update
    @isUpdateSave = CategoriesService.updateCategory(params[:id], category_params)
    if @isUpdateSave
      redirect_to categories_path
    else
      render :edit
    end
  end

  def destroy
    CategoriesService.deleteCategory(params[:id])
    redirect_to categories_path
  end

  def export
    @categories = CategoriesService.listAll

    respond_to do |format|
      format.html
      format.csv { send_data @categories.to_csv, filename: "categories-#{Date.today}.csv" }
    end
  end

  def import; end

  def import_file
    return redirect_to request.referer, notice: 'No file added' if params[:file].nil?

    unless params[:file].content_type == 'text/csv'
      return redirect_to request.referer,
                         notice: 'Only CSV files allowed'
    end

    msg = Category.import(params[:file])
    if msg != 'error'
      redirect_to categories_path
    else
      flash.now[:notice] = 'Errors occured!'
      render :import
    end
  end

  private

  def category_params
    params.require(:category).permit(:name)
  end
end

app/helpers/category_helper.rb
module CategoryHelper
end

app/views/categories/_form.html.erb
<%= bootstrap_form_for(category) do |f| %>
  <%= f.text_field :name, label: "Name", placeholder: "Enter category name" %>
  <%= f.submit "Save", class: ["btn btn-sm btn-primary"] %>
<% end %>

app/views/categories/edit.html.erb
<div class="container">
  <div class="row mt-5">
    <div class="col-6 mx-auto px-3">
      <div class="card">
        <div class="card-header">
          <h5 class="fw-bolder">Category Edit</h5>
        </div>
        <div class="card-body">
          <%= render 'form', category: @category %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/categories/import.html.erb
<div class="container">
  <div class="row mt-5">
    <div class="col-6 mx-auto">
      <div class="card">
        <div class="card-header">
          <h5 class="fw-bolder">Category Import</h5>
        </div>
        <div class="card-body">
          <% flash.each do |name, msg| %>
            <div class="text-danger mb-3">
              *<%= msg %>
            </div>
          <% end %>
          <%= form_tag categories_import_path, method: :post, multipart: true do %>
            <%= file_field_tag :file, accept: ".csv" %>
            <%= submit_tag "⚙️ Import" %>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/categories/index.html.erb
<div class="container">
  <div class="row mt-5">
    <div class="col-8 mx-auto">
      <div class="mb-3">
        <%= link_to "Create",
        new_category_path,
        method: :get,
        class: "btn btn-sm btn-primary" %>
        <%= link_to "Export",
        categories_export_path(format: "csv"),
        method: :get,
        class: "btn btn-sm btn-info" %>
        <%= link_to "Import",
        categories_import_path,
        method: :get,
        class: "btn btn-sm btn-secondary" %>
      </div>
      <table class="table table-striped table-hover">
        <thead>
          <tr>
            <th scope="col">#</th>
            <th scope="col" style="width: 40%;">Name</th>
            <th scope="col">
              Actions
            </th>
          </tr>
        </thead>
        <tbody>
          <% @categories.each do |c| %>
            <tr>
              <th scope="row"><%= c[:id] %></th>
              <td style="width: 40%;"><%= c[:name] %></td>
              <td>
                <%= link_to "Edit",
                "/categories/#{c[:id]}/edit",
                method: :get,
                class: "btn btn-sm btn-outline-success me-2  mb-sm-2" %>
                <%= button_to "Delete",
                category_path(c),
                data: {
                  confirm: "Are you sure?",
                  turbo_confirm: "Are you sure?"
                },
                method: :delete,
                class: "btn btn-sm btn-outline-danger" %>
              </td>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>
</div>

app/views/categories/new.html.erb
<div class="container">
  <div class="row mt-5">
    <div class="col-6 mx-auto px-3">
      <div class="card">
        <div class="card-header">
          <h5 class="fw-bolder">Category Create</h5>
        </div>
        <div class="card-body">
          <%= render 'form', category: @category %>
        </div>
      </div>
    </div>
  </div>
</div>