config/routes.rb
Rails.application.routes.draw do
  root 'posts#index'

  get 'categories/export', to: 'categories#export'
  get 'categories/import', to: 'categories#import'
  post 'categories/import', to: 'categories#import_file'
  get 'posts/export', to: 'posts#export'
  get 'posts/import', to: 'posts#import'
  post 'posts/import', to: 'posts#import_file'
  resources :posts do
    get '/page/:page', action: :index, on: :collection
  end
  resources :users, only: %i[new create]
  resources :categories


  # get 'users/new'
  # get 'users/create'

  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  get 'welcome', to: 'sessions#welcome'
  delete '/logout',  to: 'sessions#destroy'
  get 'authorized', to: 'sessions#page_requires_login'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/views/layouts/_navigation.html.erb
<nav class="navbar navbar-expand-lg navbar-light" style="background-color: #f0f0f0;">
  <div class="container">
    <h1 class="navbar-brand">
      <a class="navbar-brand" href="#">Blog</a>
    </h1>
    <button
      class="navbar-toggler"
      type="button"
      data-bs-toggle="collapse"
      data-bs-target="#navbarTogglerDemo01"
      aria-controls="navbarTogglerDemo01"
      aria-expanded="false"
      aria-label="Toggle navigation"
    >
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse navbar-right d-lg-flex justify-content-end" id="navbarTogglerDemo01">
      <ul class="navbar-nav">
        <% if !logged_in %>
          <li class="nav-item">
            <%= link_to "Login", login_path, method: :get, class: "nav-link" %>
          </li>
          <li class="nav-item">
            <%= link_to "Signup", new_user_path, method: :get, class: "nav-link" %>
          </li>
        <% else %>
          <li class="nav-item">
            <%= link_to "Category", categories_path, method: :get, class: "nav-link" %>
          </li>
          <li class="nav-item">
            <%= link_to "Post", posts_path, method: :get, class: "nav-link" %>
          </li>
          <li class="nav-item">
            <%= link_to "Logout", logout_path, method: :delete, class: "nav-link" %>
          </li>
        <% end %>
      </ul>
    </div>

  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>SessionAuthentication</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= render "layouts/navigation"%>
    <%= yield %>
   
  </body>
</html>